---
title: "CSUF Statistics using CourseKata"
---

Welcome! Choose a deck:

::: {.panel-tabset}

## Presentations

- [Chapter 2 (Sections 1–7)](presentations/CK-ch2.1-2.7.html)
- [Chapter 2 (Sections 8–11)](presentations/CK-ch2.8-2.11.html)
- [Chapter 3 (Sections 1-9)](presentations/CK-ch3.1-3.9.html)
- [Chapter 3 (Sections 10-13)](presentations/CK-ch3.10-3.13.html)
- [Chapter 4](presentations/CK-ch4-full.html)
- [Chapter 5](presentations/CK-ch5-full.html)
- [Chapter 6 (Sections 1-4)](presentations/CK-ch6_1-4.html)
- [Chapter 6 (Added Part II)](presentations/CK-ch6_II.html)
- [Chapter 6 (Added Part III)](presentations/CK-ch6_III-sec5-11.html)
- [Chapter 7 ](presentations/CK-ch7-complete.html)
- [Chapter 8 ](presentations/CK-ch8-complete.html)
- [Chapter 9 (Sections 1-8)](presentations/CK-ch9-sec1-8.html)
- [Chapter 9 (Sections 9-11)](presentations/CK-ch9-sec9-11.html)
- [Chapter 10](presentations/CK-ch10-complete.html)
- [Chapter 11 (Section 1-9)](presentations/CK-ch11-sec1-9.html)
- [Chapter 11 (Section 10-13)](presentations/CK-ch11-sec11-13.html)

## Preparations

- [Sample Exam 1](preparations/Exam1-Prep.html)
- [Exam 2 Study Guide](preparations/Exam2-Study-Guide.html)
- [Sample Exam 2](preparations/Exam2-Sample.html)

:::
