---
title: "CourseKata Chapter x"
subtitle: "Chapter X Topic"
author: "Mansour Abdoli, PhD"
format:
  live-revealjs:
    slide-number: true
    incremental: true
    chalkboard: true
    preview-links: true
    code-overflow: wrap
    footer: "CourseKata Ch. X"
#resources:
#  - assets/webr_helpers.R
engine: knitr
execute:
  echo: true
  warning: false
  message: false
output-files: CK-ch-x.html
---

# Today: Overview

{{< include ./_extensions/r-wasm/live/_knitr.qmd >}}

```{r}
#| echo: false
suppressPackageStartupMessages({
  library(mosaic)
  library(ggformula)
})
```

```{r}
#| echo: false
#| results: 'asis'
# create a webr to read the data
source('./data/embedData.R')
source('./assets/utils.R')
load(file = "./data/Fingers.rda")
cat(embedData(Fingers))

# for more data:
## load(file =) # load a dataset
## cat(embedData(dataset)) # Embed it 

```

```{webr}
#| echo: false
#| output: false
#| warning: false
#| message: false

library(mosaic)
library(ggformula)
options(digits = 3)

# Load helper functions if present (optional)
helpers <- readLines("assets/webr_helpers.R", warn = FALSE)
eval(parse(text = helpers))

Fingers$MathAnxious <- 
  factor(Fingers$MathAnxious,
  levels=c('Strongly Disagree', 
    'Disagree', 
    'Neither Agree nor Disagree', 
    'Agree', 'Strongly Agree'))
Fingers$Job <- 
  factor(Fingers$Job,
         c("Not Working", "Part-time Job", "Full-time Job"))

.webr_ready <- TRUE
```


## Session goals

:::{.nonincremental}
By the end of today, you can:

- do 1
- do 2
- know 3

:::

# First Topic

## Sub-Topic

- A
- B

:::{.fragment}
```{webr}
#| fig-height: 2.5
#| alt-text: "Something" # note sure if the syntax is correct
gf_points(Ring~Thumb, data=Fingers)
```
:::



